
name: CMake Build

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ctest -c 

  build:
    name: Build sim
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Prod
        # Build your program with the given configuration
        # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        run: make waves

